version: '3.7'
services:
  web:
    container_name: payment-webhook-api
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npm run start"
